# -*- coding: utf-8 -*-
"""MapQuiz 內容建置器（V2.5.0）
data-src/*.json（單一真相，含 angle 標籤）→ data/*.js（GENERATED 交付檔，純字串）
- deltas/*.json 先合併（只增不改，撞重複整批中止），成功後歸檔 deltas/applied/
- 產 data-src/manifest.json（條數、來源雜湊、時間）供 validate 對帳
用法：python3 tools/build.py   （於專案根目錄）
"""
import json, hashlib, os, shutil, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data-src")
OUT = os.path.join(ROOT, "data")
DELTAS = os.path.join(ROOT, "deltas")
SCHEMA = 1

SOURCES = ["facts-world", "facts-taiwan", "lm-desc-world", "lm-desc-taiwan",
           "landmarks-world", "landmarks-taiwan", "capitals", "flags"]
TAGGED = {"facts-world", "facts-taiwan", "lm-desc-world", "lm-desc-taiwan"}  # [{text,angle}]

def load(name):
    p = os.path.join(SRC, name + ".json")
    d = json.load(open(p))
    if d.get("schema_version") != SCHEMA:
        sys.exit("[build] %s schema_version=%s 不被本工具支援（預期 %s）" % (name, d.get("schema_version"), SCHEMA))
    return d["items"]

def save(name, items):
    json.dump({"schema_version": SCHEMA, "items": items},
              open(os.path.join(SRC, name + ".json"), "w"), ensure_ascii=False, indent=1)

def merge_deltas(data):
    """deltas/*.json: {"target":"facts-world","items":{key:[entry,...]}} 只增不改。"""
    applied = []
    for fn in sorted(os.listdir(DELTAS)):
        if not fn.endswith(".json"):
            continue
        p = os.path.join(DELTAS, fn)
        d = json.load(open(p))
        t = d["target"]
        if t not in data:
            sys.exit("[delta] %s 目標資料集不存在：%s" % (fn, t))
        for k, entries in d["items"].items():
            data[t].setdefault(k, [])
            for e in entries:
                key_text = e["text"] if isinstance(e, dict) else e
                existing = [x["text"] if isinstance(x, dict) else x for x in data[t][k]]
                if key_text in existing:
                    sys.exit("[delta] %s 重複條目，整批中止：%s/%s" % (fn, k, key_text))
                data[t][k].append(e)
        applied.append(fn)
    for fn in applied:
        shutil.move(os.path.join(DELTAS, fn), os.path.join(DELTAS, "applied", fn))
        print("[delta] applied:", fn)
    return data

def flat(items):  # [{text,angle}] -> [text]
    return {k: [e["text"] if isinstance(e, dict) else e for e in v] for k, v in items.items()}

def js(varname, obj):
    return "window.%s = %s;\n" % (varname, json.dumps(obj, ensure_ascii=False, indent=1))

def main():
    data = {n: load(n) for n in SOURCES}
    data = merge_deltas(data)
    for n in SOURCES:  # 寫回（deltas 併入後 data-src 即最新全量）
        save(n, data[n])

    wf, tf = flat(data["facts-world"]), flat(data["facts-taiwan"])
    wd, td = flat(data["lm-desc-world"]), flat(data["lm-desc-taiwan"])
    wl, tl = data["landmarks-world"], data["landmarks-taiwan"]
    caps, flags = data["capitals"], data["flags"]
    capmap = {v: k for k, v in caps.items() if k not in v}  # 坑 P7：首都含國名不入題

    def hdr(desc):
        return "/* GENERATED by tools/build.py — 勿手改，編輯 data-src/ 後重建。%s */\n" % desc

    files = {
        "world-facts.js": hdr("世界小知識 %d 條" % sum(len(v) for v in wf.values())) + js("WORLD_FACTS", wf),
        "taiwan-facts.js": hdr("台灣縣市小知識 %d 段＋景點說明 %d 句" % (sum(len(v) for v in tf.values()), sum(len(v) for v in td.values()))) + js("TW_FACTS", tf) + js("TW_LM_DESC", td),
        "world-landmarks.js": hdr("世界地標 %d 個＋說明 %d 句" % (sum(len(v) for v in wl.values()), sum(len(v) for v in wd.values()))) + js("WORLD_LANDMARKS", wl) + js("WORLD_LM_DESC", wd),
        "landmarks.js": hdr("台灣景點 %d 個" % sum(len(v) for v in tl.values())) + js("LANDMARKS", tl),
        "world-capitals.js": hdr("首都 %d／出題池 %d（排除含國名者）" % (len(caps), len(capmap))) + js("WORLD_CAPITALS", caps) + js("CAPMAP", capmap),
        "world-flags.js": hdr("旗幟 emoji %d 面" % len(flags)) + js("WORLD_FLAGS", flags),
    }
    for fn, content in files.items():
        open(os.path.join(OUT, fn), "w").write(content)

    manifest = {
        "built_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "schema_version": SCHEMA,
        "counts": {n: sum(len(v) for v in data[n].values()) if isinstance(next(iter(data[n].values())), list) else len(data[n]) for n in SOURCES},
        "source_sha256": {n: hashlib.sha256(open(os.path.join(SRC, n + ".json"), "rb").read()).hexdigest()[:16] for n in SOURCES},
        "outputs": sorted(files.keys()),
    }
    json.dump(manifest, open(os.path.join(SRC, "manifest.json"), "w"), ensure_ascii=False, indent=1)
    print("[build] OK:", ", ".join("%s=%s" % (k, v) for k, v in manifest["counts"].items()))

if __name__ == "__main__":
    main()
